CREATE DATABASE AutoTrade

USE AutoTrade

CREATE TABLE EMPLOYEES
( Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
  Username VARCHAR(60) NOT NULL UNIQUE,
  Password VARCHAR(60) NOT NULL,
  FirstName VARCHAR(60) NOT NULL,
  LastName VARCHAR(60) NOT NULL,
  Age INT NOT NULL,
  Birthday DATE NOT NULL,
  Email VARCHAR(60) NOT NULL UNIQUE
)

CREATE TABLE CUSTOMERS
( Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
  FirstName VARCHAR(60) NOT NULL,
  LastName VARCHAR(60) NOT NULL,
  EGN VARCHAR(10) NOT NULL UNIQUE, 
  Phone VARCHAR(20) NOT NULL UNIQUE,
  Address text NOT NULL,
  EmployeeId INT DEFAULT 1 NOT NULL FOREIGN KEY REFERENCES EMPLOYEES(Id)
  ON DELETE SET DEFAULT
)


CREATE TABLE CARS
(Id INT PRIMARY KEY IDENTITY(1, 1),
 Make VARCHAR(50) NOT NULL,
 Model VARCHAR(50) NOT NULL,
 Year INT NOT NULL CHECK(Year>1980),
 Price DECIMAL(8,2) NOT NULL CHECK (Price>0),
 Color VARCHAR(50) NULL
)

CREATE TABLE SALES
(Id VARCHAR(20) PRIMARY KEY NOT NULL,
CarId INT NOT NULL,
CarName VARCHAR(100) NOT NULL,
CustomerId INT NOT NULL FOREIGN KEY REFERENCES CUSTOMERS(Id)
ON DELETE NO ACTION,
SaleDate DATE NOT NULL,
EmployeeId INT NOT NULL FOREIGN KEY REFERENCES EMPLOYEES(Id),
)

CREATE TABLE RENTACAR
(Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CarId INT NOT NULL FOREIGN KEY REFERENCES CARS(Id)
ON UPDATE CASCADE ON DELETE CASCADE,
PricePerDay DECIMAL(8,2) NOT NULL CHECK (PricePerDay>0),
Status VARCHAR(100) NOT NULL
)

CREATE TABLE RENTS
(Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CarId INT NOT NULL,
CustomerId INT NOT NULL FOREIGN KEY REFERENCES CUSTOMERS(Id)
ON DELETE NO ACTION,
RentStart DATE NOT NULL,
RentEnd DATE NOT NULL,
PriceInTotal DECIMAL(8,2) NOT NULL CHECK(PriceInTotal>0),
EmployeeId INT NOT NULL FOREIGN KEY REFERENCES EMPLOYEES(Id),
)


SELECT* FROM CARS
ORDER BY Id
SELECT* FROM SALES
SELECT* FROM CUSTOMERS
ORDER BY EmployeeId
Order by EmployeeId
SELECT* FROM EMPLOYEES
SELECT* FROM RENTS

SELECT R.Id, CarId, C.Make+' '+C.Model AS CAR_NAME, PricePerDay, Status
FROM RENTACAR R JOIN CARS C
ON R.CarId=C.Id


SELECT C.Id, C.FirstName, C.LastName, C.EGN, C.Phone, Address,E.FirstName+' '+E.LastName AS EMPLOYEE_NAME
FROM CUSTOMERS C JOIN EMPLOYEES E
ON C.EmployeeId=E.Id

 SELECT
  R.Id,
  CarId,
  CustomerId,
  RentStart,
  RentEnd,
  R.EmployeeId,
  E.FirstName+' '+E.LastName AS EMPLOYEE_NAME
FROM
  RENTS R JOIN EMPLOYEES E
  ON R.EmployeeId=E.Id

SELECT
  Id,
  FirstName,
  LastName,
  EGN,
  Phone,
  Address
FROM
  CUSTOMERS
WHERE
  EmployeeId = 2

  DELETE FROM CARS
  WHERE Id=11

  SELECT
  S.Id,
  CarId,
  CarName,
  CustomerId,
  SaleDate,
  S.EmployeeId,
  E.FirstName+' '+E.LastName AS EMPLOYEE_NAME
FROM
  SALES S JOIN EMPLOYEES E
  ON S.EmployeeId=E.Id
ORDER BY SaleDate DESC

delete from CARS
where id=12